[package]
name = "sideloom"
version = "1.1.1"
description = "Mac-first IPA inspector, customizer, signer, and installer"
authors = ["nab138"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "sideloom_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["tauri-ui"]
tauri-ui = [
    "dep:tauri-build",
    "dep:tauri",
    "dep:tauri-plugin-opener",
    "dep:tauri-plugin-store",
    "dep:tauri-plugin-dialog",
    "dep:tauri-plugin-process",
    "dep:tauri-plugin-autostart",
    "dep:keyring",
]

[build-dependencies]
tauri-build = { version = "2", features = [], optional = true }

[dependencies]
tauri = { version = "2", features = ["devtools"], optional = true }
tauri-plugin-opener = { version = "2", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
idevice = { version = "0.1.57", default-features = false, features = ["ring", "usbmuxd", "house_arrest", "afc", "core_device_proxy", "remote_pairing", "tcp", "tunnel_tcp_stack", "xpc", "rsd", "pair"] }
isideload = { version = "0.3.17", default-features = false, features = ["fs-storage", "install", "tokio-mt"], git = "https://github.com/nab138/isideload", package = "isideload", branch = "apple-codesign-quick" }
keyring = { version = "3.6.3", features = ["apple-native", "windows-native", "linux-native-sync-persistent"], optional = true }
tauri-plugin-store = { version = "2", optional = true }
futures = "0.3.31"
once_cell = "1.21.3"
tauri-plugin-dialog = { version = "2", optional = true }
reqwest = { version = "0.13.2", default-features = false, features = ["rustls-no-provider", "http2", "system-proxy"] }
tokio = "1.49.0"
tauri-plugin-process = { version = "2", optional = true }
tauri-plugin-autostart = { version = "2", optional = true }
chrono = "0.4"
tracing-subscriber = "0.3.22"
tracing = "0.1.44"
tracing-appender = "0.2"
rustls = { version = "0.23.36", default-features = false, features = ["ring", "std", "tls12"] }
plist = "1.8.0"
plist-macro = "0.1.6"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "webp"] }
tokio-util = "0.7.18"
rootcause = "0.12.1"
thiserror = "2.0.18"
strum = {version = "0.28.0", features = ["derive"] }
